version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - IMAGE_TAG=latest
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test -P production
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests=true
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Building Docker Image...
      - cp target/petclinic.jar ./tomcat/
      - echo Building Docker Image...
      - docker build --tag petclinic-web:latest ./tomcat
      - docker tag petclinic-web:latest ${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - echo Pushing Docker Image...
      - docker push ${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - printf '[{"name":"pet-container","imageUri":"%s"}]' ${IMAGE_REPO_NAME}:${IMAGE_TAG} > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

